name: caddy

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/binary.yaml'
  schedule:
    - cron: "0 0 * * Sat"
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Setup Go
      uses: actions/setup-go@master
      with:
        check-latest: true

    - name: install
      run: |
        go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest

    - name: xcaddy
      run: |
        export GOPATH=$HOME/go
        export PATH=$PATH:$GOPATH/bin
        echo CaddyVer=${version} >>$GITHUB_ENV
        for arch in amd64 arm64
        do
          GOOS=linux GOARCH=${arch} \
          xcaddy build latest --output caddy_linux-${arch} \
          --with github.com/caddy-dns/cloudflare \
          --with github.com/greenpau/caddy-security \
          --with github.com/mholt/caddy-l4 \
          --with github.com/abiosoft/caddy-yaml \
          --with github.com/caddyserver/replace-response \  & 
          GOOS=freebsd GOARCH=${arch} \
          xcaddy build latest --output caddy_freebsd-${arch}  \
          --with github.com/caddy-dns/cloudflare \
          --with github.com/greenpau/caddy-security \
          --with github.com/mholt/caddy-l4 \
          --with github.com/abiosoft/caddy-yaml \
          --with github.com/caddyserver/replace-response \
        zstd -k -19 caddy_linux-${arch} -o caddy_linux-${arch}.zst
        zstd -k -19 caddy_freebsd-${arch} -o caddy_freebsd-${arch}.zst
        done

    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: caddy
        path: ./

    - name: fin
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ env.CaddyVer }}
        body: caddy ${{ env.CaddyVer }}
        file: ./caddy_-*
        overwrite: true
        file_glob: true
